FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock

COPY ./packages ./packages
COPY ./turbo.json ./turbo.json

COPY ./apps/ws-server ./apps/ws-server

RUN bun install
RUN bun run db:generate

EXPOSE 3002

CMD ["bun", "run", "start:ws"]