# Issues with Next.js - Hot Reloading with Docker needs to be checked out
#                     - Static Site Generation needs to be checked out
#                     - Server Side Rendering needs to be checked out

FROM oven/bun:1

WORKDIR /usr/src/app

ARG DATABASE_URL

COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock

COPY ./packages ./packages
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web

RUN bun install

RUN bun run db:generate
RUN DATABASE_URL=$DATABASE_URL bun run build

EXPOSE 3000

CMD ["bun", "run", "start:web"]